//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int id { get; set; }
        public int customerId { get; set; }
        public System.DateTime orderDate { get; set; }
        public Nullable<System.DateTime> shippedDate { get; set; }
        public decimal sumPurchase { get; set; }
        public decimal Shipping { get; set; }
        public decimal sumShipping { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
